/**************************************************************************
 * <pre>
 *     FileName: z.z.w.project.test.service.SystemDataService.java
 *         Desc: 
 *      @author: Wu Zhenzhen - myhongkongzhen@gmail.com
 *     @version: 2013-11-4 下午04:17:30 
 *   LastChange: 2013-11-4 下午04:17:30 
 *      History:
 * </pre>
 **************************************************************************/
package z.z.w.project.test.service;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.stereotype.Service;

import z.z.w.project.test.dao.SystemDataDao;
import z.z.w.project.test.model.SystemData;
import z.z.w.project.util.common.DateTools;

/**
 * z.z.w.project.test.service.SystemDataService.java
 */
@Service
public class SystemDataService {

	private SystemDataDao<SystemData> systemDataDao;

	/**
	 * <br>
	 * Created on: 2013-11-4 下午04:22:40
	 * 
	 * @return the systemDataDao
	 */
	public SystemDataDao<SystemData> getSystemDataDao() {
		return systemDataDao;
	}

	/**
	 * <br>
	 * Created on: 2013-11-4 下午04:22:40
	 * 
	 * @param systemDataDao
	 *            the systemDataDao to set
	 */
	@Resource
	public void setSystemDataDao(SystemDataDao<SystemData> systemDataDao) {
		this.systemDataDao = systemDataDao;
	}

	/**
	 * <br>
	 * Created on: 2013-11-4 下午08:23:06
	 * 
	 * @return
	 */
	public List<SystemData> queryList() {
		List<SystemData> list = new ArrayList<SystemData>();
		SystemData sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("信用卡");
		sd.setLeixing("買菜");
		sd.setMoney(30.5f);
		sd.setNote("大白菜");
		sd.setShouzhi("支出");
		sd.setXingzhi("食");
		list.add(sd);

		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("現金");
		sd.setLeixing("買菜");
		sd.setMoney(20.5f);
		sd.setNote("大白菜");
		sd.setShouzhi("支出");
		sd.setXingzhi("食");
		list.add(sd);

		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("信用卡");
		sd.setLeixing("外出就餐");
		sd.setMoney(10.5f);
		sd.setNote("午餐");
		sd.setShouzhi("支出");
		sd.setXingzhi("食");
		list.add(sd);

		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("工資卡");
		sd.setLeixing("工資");
		sd.setMoney(30000f);
		sd.setNote("5月份工資");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);

		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(1);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("存摺");
		sd.setLeixing("轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("其他");
		list.add(sd);
		sd = new SystemData();
		sd.setId(100);
		sd.setDataDate(DateTools.getCurrentDate());
		sd.setJiezhi("最後的記錄存摺");
		sd.setLeixing("最後的記錄轉賬");
		sd.setMoney(11130.5f);
		sd.setNote("最後的記錄轉賬");
		sd.setShouzhi("收入");
		sd.setXingzhi("最後的記錄其他");
		list.add(sd);

		return list;
	}

}
