package com.symbol.wp.core.dto;

import com.symbol.wp.core.entity.TbBasePermissions;

/**
 * Userinfo generated by MyEclipse Persistence Tools
 */

public class BasePermisView extends TbBasePermissions implements
		java.io.Serializable {
	private String parentMenuName; // 父菜单
	private String parentPermisName; // 父权限名

	public String getParentMenuName() {
		return parentMenuName;
	}

	public void setParentMenuName(String parentMenuName) {
		this.parentMenuName = parentMenuName;
	}

	public String getParentPermisName() {
		return parentPermisName;
	}

	public void setParentPermisName(String parentPermisName) {
		this.parentPermisName = parentPermisName;
	}
}