package com.symbol.wp.core.dto;

import com.symbol.wp.core.entity.TbBaseRoles;
import com.symbol.wp.core.entity.TbBaseUserInfo;
import com.symbol.wp.core.entity.TbBaseUserRole;

/**
 * Userinfo generated by MyEclipse Persistence Tools
 */

public class UserAllinfoView implements java.io.Serializable {
	public TbBaseUserInfo userinfo = null;
	public TbBaseRoles baseRoles = null;
	public TbBaseUserRole baseUserRole = null;
	public TbBaseUserInfo getUserinfo() {
		return userinfo;
	}
	public void setUserinfo(TbBaseUserInfo userinfo) {
		this.userinfo = userinfo;
	}
	public TbBaseRoles getBaseRoles() {
		return baseRoles;
	}
	public void setBaseRoles(TbBaseRoles baseRoles) {
		this.baseRoles = baseRoles;
	}
	public TbBaseUserRole getBaseUserRole() {
		return baseUserRole;
	}
	public void setBaseUserRole(TbBaseUserRole baseUserRole) {
		this.baseUserRole = baseUserRole;
	}
}