package com.symbol.wp.core.dto;

import com.symbol.wp.core.entity.TbBasePermissions;

/**
 * Userinfo generated by MyEclipse Persistence Tools
 */

public class VBasePermissions extends TbBasePermissions implements
		java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -6122100633875936275L;
	private String parentMenuName; // ���˵�
	private String parentPermisName; // ��Ȩ����

	public String getParentMenuName() {
		return parentMenuName;
	}

	public void setParentMenuName(String parentMenuName) {
		this.parentMenuName = parentMenuName;
	}

	public String getParentPermisName() {
		return parentPermisName;
	}

	public void setParentPermisName(String parentPermisName) {
		this.parentPermisName = parentPermisName;
	}
}