-------------------
truncate table tbBasePermissions;
truncate table tbBaseRolePermis;
truncate table tbBaseRoles;
truncate table tbBaseUserInfo;
truncate table tbBaseUserRole;
truncate table tbBaseRoleGroup;
truncate table tbBaseDepartment;
commit;
--------------------
--tbBasePermissions
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BASE_BUSINUSS_MANA','BASE','业务分析','#',1,' ','0',1,'1','BASE_BUSINUSS_MANA') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BASE_TERMINAL_MANA','BASE','终端分析','#',2,' ','0',1,'1','BASE_TERMINAL_MANA') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BASE_MMS_MANA','BASE','彩信分析','#',3,' ','0',1,'1','BASE_MMS_MANA') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BASE_BB_MANA','BASE','黑莓分析','#',4,' ','0',1,'1','BASE_BB_MANA') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BASE_RULE_MANA','BASE','规则管理','#',5,' ','0',1,'1','BASE_RULE_MANA') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BASE_SYSTEM_MANA','BASE','系统管理','#',6,' ','0',1,'1','BASE_SYSTEM_MANA') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BUSINUSS_FLUSH','BASE_BUSINUSS_MANA','全网业务分析','#',1,' ','0',1,'1','BUSINUSS_FLUSH') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BUSINUSS_GROUP_FLUSH','BASE_BUSINUSS_MANA','集团业务分析','#',2,' ','0',1,'1','BUSINUSS_GROUP_FLUSH') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BUSINUSS_BIG_FLUSH','BASE_BUSINUSS_MANA','大流量行为分析','#',3,' ','0',1,'1','BUSINUSS_BIG_FLUSH') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BUSINUSS_DATA_CATCH','BASE_BUSINUSS_MANA','用户数据提取','#',4,' ','0',1,'1','BUSINUSS_DATA_CATCH') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('FLUSH_TOTAL_DIST','BUSINUSS_FLUSH','全网业务分析','/mantoeye/data_analyse/total_distribute.jsp?1=1',1,' ','0',1,'1','FLUSH_TOTAL_DIST') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('FLUSH_SPACE_DIST','BUSINUSS_FLUSH','空间分布','/mantoeye/data_analyse/space_distribute.jsp?1=1',2,' ','0',1,'1','FLUSH_SPACE_DIST') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('FLUSH_BUSI_DIST','BUSINUSS_FLUSH','业务分布','/mantoeye/data_analyse/business_distribute.jsp?1=1',3,' ','0',1,'1','FLUSH_BUSI_DIST') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('FLUSH_APN_DIST','BUSINUSS_FLUSH','APN分布','/mantoeye/data_analyse/apn.jsp?1=1',4,' ','0',1,'1','FLUSH_APN_DIST') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('FLUSH_WAP_DIST','BUSINUSS_FLUSH','应用协议分布','/mantoeye/data_analyse/wap.jsp?1=1',5,' ','0',1,'1','FLUSH_WAP_DIST') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('FLUSH_TCP_DIST','BUSINUSS_FLUSH','传输协议分布','/mantoeye/data_analyse/tcp.jsp?1=1',6,' ','0',1,'1','FLUSH_TCP_DIST') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('FLUSH_COUNTRY_DIST','BUSINUSS_FLUSH','用户归属分布','/mantoeye/data_analyse/userAttach.jsp?1=1',7,' ','0',1,'1','FLUSH_COUNTRY_DIST') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('FLUSH_TOPFLUSH_DIST','BUSINUSS_FLUSH','流量TOP100小区','/mantoeye/data_analyse/topflush.jsp?1=1',8,' ','0',1,'1','FLUSH_TOPFLUSH_DIST') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('FLUSH_TOPUSER_DIST','BUSINUSS_FLUSH','用户数TOP100小区','/mantoeye/data_analyse/topuser.jsp?1=1',9,' ','0',1,'1','FLUSH_TOPUSER_DIST') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('GROUP_APNSPACE_DIST','BUSINUSS_GROUP_FLUSH','APN空间分布','/mantoeye/groupBisness/areadistribute.jsp?1=1',1,' ','0',1,'1','GROUP_APNSPACE_DIST') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('GROUP_APN_DIST','BUSINUSS_GROUP_FLUSH','APN分布','/mantoeye/bloc_analyse/bloc_apn.jsp?1=1',2,' ','0',1,'1','GROUP_APN_DIST') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('GROUP_COUNTRY_DIST','BUSINUSS_GROUP_FLUSH','用户归属分布','/mantoeye/groupBisness/groupbisuserbelong.jsp?1=1',3,' ','0',1,'1','GROUP_COUNTRY_DIST') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BIG_USER_MANA','BUSINUSS_BIG_FLUSH','大流量用户','/mantoeye/valueset/big_flush_display.jsp?1=1',1,' ','0',1,'1','BIG_USER_MANA') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BIG_BLACK_MANA','BUSINUSS_BIG_FLUSH','黑名单管理','/mantoeye/valueset/blackuser.jsp?1=1',2,' ','0',1,'1','BIG_BLACK_MANA') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BIG_FILTER_MANA','BUSINUSS_BIG_FLUSH','大流量阀值设置','/mantoeye/valueset/limitvalue.jsp?1=1',3,' ','0',1,'1','BIG_FILTER_MANA') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('CATCH_HISBASE_DATA','BUSINUSS_DATA_CATCH','历史原始数据提取','/mantoeye/data_catch/data_catch_index.jsp?1=1',1,' ','0',1,'1','CATCH_HISBASE_DATA') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('CATCH_CURRBASE_DATA','BUSINUSS_DATA_CATCH','实时原始数据提取','/mantoeye/data_catch/data_catch_index.jsp?1=1',2,' ','0',1,'1','CATCH_CURRBASE_DATA') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('CATCH_HISANALYSIS_DATA','BUSINUSS_DATA_CATCH','历史解析记录提取','/mantoeye/data_catch/data_catch_index.jsp?1=1',3,' ','0',1,'1','CATCH_HISANALYSIS_DATA') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('CATCH_IMSIS_DATA','BUSINUSS_DATA_CATCH','用户号码提取','/mantoeye/data_catch/data_catch_index.jsp?1=1',4,' ','0',1,'1','CATCH_IMSIS_DATA') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('TERMINAL_BUSI_ANAY','BASE_TERMINAL_MANA','终端业务分析','/mantoeye/terminalbisanlyse/terminalanalyse.jsp?1=1',1,' ','0',1,'1','TERMINAL_BUSI_ANAY') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BUSINUSS_TERM_ANAY','BASE_TERMINAL_MANA','业务终端分析','/mantoeye/terminalbisanlyse/businessanalyse.jsp?1=1',2,' ','0',1,'1','BUSINUSS_TERM_ANAY') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('TERMINAL_DATA_MANA','BASE_TERMINAL_MANA','终端管理','/mantoeye/terminalmanager/terminaluser.jsp?1=1',3,' ','0',1,'1','TERMINAL_DATA_MANA') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('TERMINAL_TASK_MANA','BASE_TERMINAL_MANA','终端任务定制','/mantoeye/terminalmanager/terminal_task.jsp?1=1',4,' ','0',1,'1','TERMINAL_TASK_MANA') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('MMS_TOTAL_ANAY','BASE_MMS_MANA','总体分析','#',1,' ','0',1,'1','MMS_TOTAL_ANAY') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('MMS_SP_ANAY','BASE_MMS_MANA','SP彩信','#',2,' ','0',1,'1','MMS_SP_ANAY') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('MMS_PEER_ANAY','BASE_MMS_MANA','点对点彩信','#',3,' ','0',1,'1','MMS_PEER_ANAY') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('MMS_TOTAL_TYPE_STAT','MMS_TOTAL_ANAY','发送方式统计','/mantoeye/mms/mms_send_mode.jsp?1=1',1,' ','0',1,'1','MMS_TOTAL_TYPE_STAT') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('MMS_TOTAL_HOUR_STAT','MMS_TOTAL_ANAY','流量分时段统计','/mantoeye/mms/mms_time_level.jsp?1=1',2,' ','0',1,'1','MMS_TOTAL_HOUR_STAT') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('MMS_SP_PORT_STAT','MMS_SP_ANAY','按端口统计','/mantoeye/mms/sp/sp_mms_port.jsp?1=1',1,' ','0',1,'1','MMS_SP_PORT_STAT') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('MMS_SP_TITEL_STAT','MMS_SP_ANAY','按主题统计','/mantoeye/mms/sp/sp_mms_title.jsp?1=1',2,' ','0',1,'1','MMS_SP_TITEL_STAT') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('MMS_SP_SPACE_STAT','MMS_SP_ANAY','按区域统计','/mantoeye/mms/sp/sp_mms_area.jsp?1=1',3,' ','0',1,'1','MMS_SP_SPACE_STAT') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('MMS_SP_TSPACE_STAT','MMS_SP_ANAY','按主题区域统计','/mantoeye/mms/sp/sp_mms_title_area.jsp?1=1',4,' ','0',1,'1','MMS_SP_TSPACE_STAT') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('MMS_SP_THOUR_STAT','MMS_SP_ANAY','按主题时段统计','/mantoeye/mms/sp/sp_mms_title_time.jsp?1=1',5,' ','0',1,'1','MMS_SP_THOUR_STAT') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('MMS_SP_FLEVEL_STAT','MMS_SP_ANAY','按流量分档统计','/mantoeye/mms/sp/sp_mms_flush_level.jsp?1=1',6,' ','0',1,'1','MMS_SP_FLEVEL_STAT') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('MMS_PEER_SEG_STAT','MMS_PEER_ANAY','号段分布','/mantoeye/mms/peer/mms_peer_seg.jsp?1=1',1,' ','0',1,'1','MMS_PEER_SEG_STAT') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('MMS_PEER_HOUR_STAT','MMS_PEER_ANAY','时段分布','/mantoeye/mms/peer/mms_peer_hour.jsp?1=1',2,' ','0',1,'1','MMS_PEER_HOUR_STAT') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('MMS_PEER_SPACE_STAT','MMS_PEER_ANAY','空间分布','/mantoeye/mms/peer/mms_peer_space.jsp?1=1',3,' ','0',1,'1','MMS_PEER_SPACE_STAT') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BB_AREA_ANAY','BASE_BB_MANA','区域','#',1,' ','0',1,'1','BB_AREA_ANAY') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BB_YYS_ANAY','BASE_BB_MANA','运营商','#',2,' ','0',1,'1','BB_YYS_ANAY') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BB_ACTIVE_ANAY','BASE_BB_MANA','活跃用户','#',3,' ','0',1,'1','BB_ACTIVE_ANAY') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BB_COUNTRY_ANAY','BASE_BB_MANA','用户归属','#',4,' ','0',1,'1','BB_COUNTRY_ANAY') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BB_AREA_SPACE_DIST','BB_AREA_ANAY','空间分布','/mantoeye/blackberry/bbarea.jsp?1=1',1,' ','0',1,'1','BB_AREA_SPACE_DIST') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BB_AREA_FLUSH_TOP','BB_AREA_ANAY','流量TOP100小区','/mantoeye/blackberry/top100areaflush.jsp?1=1',2,' ','0',1,'1','BB_AREA_FLUSH_TOP') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BB_YYS_USER_DEST','BB_YYS_ANAY','运营商分布','/mantoeye/blackberry/yysbusiness.jsp?1=1',1,' ','0',1,'1','BB_YYS_USER_DEST') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BB_YYS_SPACE_DEST','BB_YYS_ANAY','空间分布','/mantoeye/blackberry/areayys.jsp?1=1',2,' ','0',1,'1','BB_YYS_SPACE_DEST') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BB_ACTIVE_USER_LIST','BB_ACTIVE_ANAY','活跃用户呈现','/mantoeye/blackberry/active/bb_active.jsp?1=1',1,' ','0',1,'1','BB_ACTIVE_USER_LIST') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BB_ACTIVE_SPACE_DEST','BB_ACTIVE_ANAY','空间分布','/mantoeye/blackberry/active/bb_active_space.jsp?1=1',2,' ','0',1,'1','BB_ACTIVE_SPACE_DEST') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BB_COUNTRY_USER_DEST','BB_COUNTRY_ANAY','用户归属分布','/mantoeye/blackberry/country/bb_country.jsp?1=1',1,' ','0',1,'1','BB_COUNTRY_USER_DEST') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BB_COUNTRY_SPACE_DEST','BB_COUNTRY_ANAY','空间分布','/mantoeye/blackberry/country/bb_country_space.jsp?1=1',2,' ','0',1,'1','BB_COUNTRY_SPACE_DEST') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BB_COUNTRY_USER_TOP','BB_COUNTRY_ANAY','用户数TOP100小区','/mantoeye/blackberry/country/bb_country_top.jsp?1=1',3,' ','0',1,'1','BB_COUNTRY_USER_TOP') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('RULE_BUSI_MANA','BASE_RULE_MANA','业务配置','/mantoeye/business_rules/business_site/index.jsp?1=1',1,' ','0',1,'1','RULE_BUSI_MANA') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('RULE_MA_MANA','BASE_RULE_MANA','规则配置','#',2,' ','0',1,'1','RULE_MA_MANA') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('RULE_TEST_MANA','BASE_RULE_MANA','业务规则拨测维护','/mantoeye/business_rules/ruletest/index.jsp?1=1',3,' ','0',1,'1','RULE_TEST_MANA') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('RULE_MAINFLUSH_STAT','BASE_RULE_MANA','流量碰撞率异常统计','/mantoeye/business_rules/mainflush/index.jsp?1=1',4,' ','0',1,'1','RULE_MAINFLUSH_STAT') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('RULE_ASSIST_STAT','BASE_RULE_MANA','检验规则异常统计','/mantoeye/business_rules/assiststat/index.jsp?1=1',5,' ','0',1,'1','RULE_ASSIST_STAT') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('RULE_RECOGNISE_STAT','BASE_RULE_MANA','全量业务自发现','/mantoeye/business_rules/recognise/index.jsp?1=1',6,' ','0',1,'1','RULE_RECOGNISE_STAT') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('RULE_TOPFLUSH_STAT','BASE_RULE_MANA','业务流量统计排名','/mantoeye/business_rules/topflush/index.jsp?1=1',7,' ','0',1,'1','RULE_TOPFLUSH_STAT') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('SYSTEM_USER_MANA','BASE_SYSTEM_MANA','用户管理','/sysdata/user/user_index.jsp?1=1',1,' ','0',1,'1','SYSTEM_USER_MANA') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('SYSTEM_ROLE_MANA','BASE_SYSTEM_MANA','角色管理','/sysdata/role/role_index.jsp?1=1',2,' ','0',1,'1','SYSTEM_ROLE_MANA') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('SYSTEM_MENU_MANA','BASE_SYSTEM_MANA','模块管理','/sysdata/permis/permis_index.jsp?1=1',3,' ','0',1,'1','SYSTEM_MENU_MANA') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('SYSTEM_LOG_MANA','BASE_SYSTEM_MANA','系统日志','/sysdata/logs/log_index.jsp?1=1',4,' ','0',1,'1','SYSTEM_LOG_MANA') ; 

insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('RULE_MA_MAIN_MANA','RULE_MA_MANA','翻译规则配置','/mantoeye/business_rules/vetor/main_index.jsp?1=1',1,' ','0',1,'1','RULE_MA_MAIN_MANA') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('RULE_MA_ASSIST_MANA','RULE_MA_MANA','自发现规则配置','/mantoeye/business_rules/vetor/assist_index.jsp?1=1',2,' ','0',1,'1','RULE_MA_ASSIST_MANA') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('RULE_MA_MAMAP_MANA','RULE_MA_MANA','检验规则关联','/mantoeye/business_rules/vetor/index.jsp?1=1',3,' ','0',1,'1','RULE_MA_MAMAP_MANA') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('OFFHAND_DATA_QUERY','BASE_BUSINUSS_MANA','即席查询','/mantoeye/immediately/immediately_query.jsp?1=1',5,' ','0',1,'1','OFFHAND_DATA_QUERY') ; 

--tbBaseRolePermis
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_0','BASE_BUSINUSS_MANA','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_1','BASE_TERMINAL_MANA','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_2','BASE_MMS_MANA','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_3','BASE_BB_MANA','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_4','BASE_RULE_MANA','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_5','BASE_SYSTEM_MANA','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_6','BUSINUSS_FLUSH','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_7','BUSINUSS_GROUP_FLUSH','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_8','BUSINUSS_BIG_FLUSH','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_9','BUSINUSS_DATA_CATCH','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_10','FLUSH_TOTAL_DIST','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_11','FLUSH_SPACE_DIST','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_12','FLUSH_BUSI_DIST','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_13','FLUSH_APN_DIST','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_14','FLUSH_WAP_DIST','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_15','FLUSH_TCP_DIST','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_16','FLUSH_COUNTRY_DIST','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_17','FLUSH_TOPFLUSH_DIST','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_18','FLUSH_TOPUSER_DIST','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_19','GROUP_APNSPACE_DIST','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_20','GROUP_APN_DIST','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_21','GROUP_COUNTRY_DIST','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_22','BIG_USER_MANA','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_23','BIG_BLACK_MANA','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_24','BIG_FILTER_MANA','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_25','CATCH_HISBASE_DATA','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_26','CATCH_CURRBASE_DATA','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_27','CATCH_HISANALYSIS_DATA','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_28','CATCH_IMSIS_DATA','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_29','TERMINAL_BUSI_ANAY','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_30','BUSINUSS_TERM_ANAY','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_31','TERMINAL_DATA_MANA','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_32','TERMINAL_TASK_MANA','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_33','MMS_TOTAL_ANAY','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_34','MMS_SP_ANAY','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_35','MMS_PEER_ANAY','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_36','MMS_TOTAL_TYPE_STAT','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_37','MMS_TOTAL_HOUR_STAT','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_38','MMS_SP_PORT_STAT','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_39','MMS_SP_TITEL_STAT','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_40','MMS_SP_SPACE_STAT','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_41','MMS_SP_TSPACE_STAT','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_42','MMS_SP_THOUR_STAT','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_43','MMS_SP_FLEVEL_STAT','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_44','MMS_PEER_SEG_STAT','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_45','MMS_PEER_HOUR_STAT','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_46','MMS_PEER_SPACE_STAT','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_47','BB_AREA_ANAY','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_48','BB_YYS_ANAY','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_49','BB_ACTIVE_ANAY','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_50','BB_COUNTRY_ANAY','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_51','BB_AREA_SPACE_DIST','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_52','BB_AREA_FLUSH_TOP','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_53','BB_YYS_USER_DEST','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_54','BB_YYS_SPACE_DEST','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_55','BB_ACTIVE_USER_LIST','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_56','BB_ACTIVE_SPACE_DEST','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_57','BB_COUNTRY_USER_DEST','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_58','BB_COUNTRY_SPACE_DEST','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_59','BB_COUNTRY_USER_TOP','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_60','RULE_BUSI_MANA','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_61','RULE_MA_MANA','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_62','RULE_TEST_MANA','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_63','RULE_MAINFLUSH_STAT','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_64','RULE_ASSIST_STAT','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_65','RULE_RECOGNISE_STAT','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_66','RULE_TOPFLUSH_STAT','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_67','SYSTEM_USER_MANA','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_68','SYSTEM_ROLE_MANA','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_69','SYSTEM_MENU_MANA','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_70','SYSTEM_LOG_MANA','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_71','RULE_MA_MAIN_MANA','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_72','RULE_MA_ASSIST_MANA','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_73','RULE_MA_MAMAP_MANA','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_74','OFFHAND_DATA_QUERY','ROLEGROUP_4U00BQ7H');

----------------------------------------------
insert into tbBaseRoles  values ('ROLEGROUP_4U00BQ7H','超级管理员','超级管理员角色，用于系统的管理和维护，请不要删除和修改权限',0,'ROLEGROUP_S9EHNF05') ;
----------------------------------------------
 insert into tbBaseUserInfo  values ('BASEUSERINFO_ADMIN','admin','DEPT_ETONE','超级管理员',' ',' ',' ',0,'96e79218965eb72c92a549dd5a330112') ;
----------------------------------------------
 insert into tbBaseUserRole  values ('BASEUSERROLE_ID001','ROLEGROUP_4U00BQ7H','BASEUSERINFO_ADMIN') ;
---------------------------------------------
---------------------------------------
insert into tbBaseRoleGroup values('ROLEGROUP_S9EHNF05','超级管理员组','','');

---------------------------------------
insert into tbBaseDepartment values('DEPT_ETONE','','宜通','');

--insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('IMEI_DATA_QUERY','BUSINUSS_DATA_CATCH','IMEI数据提取','/mantoeye/data_catch/imei_catch.jsp?1=1',5,' ','0',1,'1','IMEI_DATA_QUERY') ; 
--insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_174','IMEI_DATA_QUERY','ROLEGROUP_4U00BQ7H');


--delete tbBasePermissions where tiPermType = 2

insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BIG_USER_MANA_BTN_BLACK','BIG_USER_MANA','[按钮]加入黑名单','#',1,' ','0',2,'1','BIG_USER_MANA_BTN_BLACK') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BIG_BLACK_MANA_BTN_ADD','BIG_BLACK_MANA','[按钮]添加','#',1,' ','0',2,'1','BIG_BLACK_MANA_BTN_ADD') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BIG_BLACK_MANA_BTN_EDIT','BIG_BLACK_MANA','[按钮]编辑','#',2,' ','0',2,'1','BIG_BLACK_MANA_BTN_EDIT') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BIG_BLACK_MANA_BTN_DEL','BIG_BLACK_MANA','[按钮]删除','#',3,' ','0',2,'1','BIG_BLACK_MANA_BTN_DEL') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('BIG_FILTER_MANA_BTN_EDIT','BIG_FILTER_MANA','[按钮]修改设置','#',1,' ','0',2,'1','BIG_FILTER_MANA_BTN_EDIT') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('SYSTEM_USER_MANA_BTN_ADD','SYSTEM_USER_MANA','[按钮]添加用户','#',1,' ','0',2,'1','SYSTEM_USER_MANA_BTN_ADD') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('SYSTEM_USER_MANA_BTN_EDIT','SYSTEM_USER_MANA','[按钮]编辑用户','#',2,' ','0',2,'1','SYSTEM_USER_MANA_BTN_EDIT') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('SYSTEM_USER_MANA_BTN_DEL','SYSTEM_USER_MANA','[按钮]删除用户','#',3,' ','0',2,'1','SYSTEM_USER_MANA_BTN_DEL') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('SYSTEM_USER_MANA_BTN_ROLE','SYSTEM_USER_MANA','[按钮]权限设置','#',4,' ','0',2,'1','SYSTEM_USER_MANA_BTN_ROLE') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('SYSTEM_USER_MANA_BTN_UNMP','SYSTEM_USER_MANA','[按钮]同步用户','#',5,' ','0',2,'1','SYSTEM_USER_MANA_BTN_UNMP') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('SYSTEM_ROLE_MANA_BTN_ADD','SYSTEM_ROLE_MANA','[按钮]添加角色','#',1,' ','0',2,'1','SYSTEM_ROLE_MANA_BTN_ADD') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('SYSTEM_ROLE_MANA_BTN_EDIT','SYSTEM_ROLE_MANA','[按钮]编辑角色','#',2,' ','0',2,'1','SYSTEM_ROLE_MANA_BTN_EDIT') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('SYSTEM_ROLE_MANA_BTN_DEL','SYSTEM_ROLE_MANA','[按钮]删除角色','#',3,' ','0',2,'1','SYSTEM_ROLE_MANA_BTN_DEL') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('SYSTEM_ROLE_MANA_BTN_ROLE','SYSTEM_ROLE_MANA','[按钮]权限设置','#',4,' ','0',2,'1','SYSTEM_ROLE_MANA_BTN_ROLE') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('SYSTEM_MENU_MANA_BTN_ADD','SYSTEM_MENU_MANA','[按钮]添加模块','#',1,' ','0',2,'1','SYSTEM_MENU_MANA_BTN_ADD') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('SYSTEM_MENU_MANA_BTN_EDIT','SYSTEM_MENU_MANA','[按钮]编辑模块','#',2,' ','0',2,'1','SYSTEM_MENU_MANA_BTN_EDIT') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('SYSTEM_MENU_MANA_BTN_DEL','SYSTEM_MENU_MANA','[按钮]删除模块','#',3,' ','0',2,'1','SYSTEM_MENU_MANA_BTN_DEL') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('SYSTEM_LOG_MANA_BTN_DEL','SYSTEM_LOG_MANA','[按钮]删除模块','#',3,' ','0',2,'1','SYSTEM_LOG_MANA_BTN_DEL') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('CATCH_HISBASE_DATA_BTN_ADD','CATCH_HISBASE_DATA','[按钮]添加任务','#',1,' ','0',2,'1','CATCH_HISBASE_DATA_BTN_ADD') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('CATCH_HISBASE_DATA_BTN_EDIT','CATCH_HISBASE_DATA','[按钮]编辑任务','#',2,' ','0',2,'1','CATCH_HISBASE_DATA_BTN_EDIT') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('CATCH_HISBASE_DATA_BTN_PAUSE','CATCH_HISBASE_DATA','[按钮]暂停任务','#',3,' ','0',2,'1','CATCH_HISBASE_DATA_BTN_PAUSE') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('CATCH_HISBASE_DATA_BTN_DEL','CATCH_HISBASE_DATA','[按钮]删除任务','#',4,' ','0',2,'1','CATCH_HISBASE_DATA_BTN_DEL') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('CATCH_CURRBASE_DATA_BTN_ADD','CATCH_CURRBASE_DATA','[按钮]添加任务','#',1,' ','0',2,'1','CATCH_CURRBASE_DATA_BTN_ADD') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('CATCH_CURRBASE_DATA_BTN_EDIT','CATCH_CURRBASE_DATA','[按钮]编辑任务','#',2,' ','0',2,'1','CATCH_CURRBASE_DATA_BTN_EDIT') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('CATCH_CURRBASE_DATA_BTN_PAUSE','CATCH_CURRBASE_DATA','[按钮]暂停任务','#',3,' ','0',2,'1','CATCH_CURRBASE_DATA_BTN_PAUSE') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('CATCH_CURRBASE_DATA_BTN_DEL','CATCH_CURRBASE_DATA','[按钮]删除任务','#',4,' ','0',2,'1','CATCH_CURRBASE_DATA_BTN_DEL') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('CATCH_HISANALYSIS_DATA_BTN_ADD','CATCH_HISANALYSIS_DATA','[按钮]添加任务','#',1,' ','0',2,'1','CATCH_HISANALYSIS_DATA_BTN_ADD') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('CATCH_HISANALYSIS_DATA_BTN_EDIT','CATCH_HISANALYSIS_DATA','[按钮]编辑任务','#',2,' ','0',2,'1','CATCH_HISANALYSIS_DATA_BTN_EDIT') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('CATCH_HISANALYSIS_DATA_BTN_PAUSE','CATCH_HISANALYSIS_DATA','[按钮]暂停任务','#',3,' ','0',2,'1','CATCH_HISANALYSIS_DATA_BTN_PAUSE') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('CATCH_HISANALYSIS_DATA_BTN_DEL','CATCH_HISANALYSIS_DATA','[按钮]删除任务','#',4,' ','0',2,'1','CATCH_HISANALYSIS_DATA_BTN_DEL') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('CATCH_IMSIS_DATA_BTN_ADD','CATCH_IMSIS_DATA','[按钮]添加任务','#',1,' ','0',2,'1','CATCH_IMSIS_DATA_BTN_ADD') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('CATCH_IMSIS_DATA_BTN_EDIT','CATCH_IMSIS_DATA','[按钮]编辑任务','#',2,' ','0',2,'1','CATCH_IMSIS_DATA_BTN_EDIT') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('CATCH_IMSIS_DATA_BTN_PAUSE','CATCH_IMSIS_DATA','[按钮]暂停任务','#',3,' ','0',2,'1','CATCH_IMSIS_DATA_BTN_PAUSE') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('CATCH_IMSIS_DATA_BTN_DEL','CATCH_IMSIS_DATA','[按钮]删除任务','#',4,' ','0',2,'1','CATCH_IMSIS_DATA_BTN_DEL') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('TERMINAL_DATA_MANA_BTN_UPLOAD','TERMINAL_DATA_MANA','[按钮]上传终端','#',1,' ','0',2,'1','TERMINAL_DATA_MANA_BTN_UPLOAD') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('TERMINAL_DATA_MANA_BTN_CLEAR','TERMINAL_DATA_MANA','[按钮]清除终端','#',2,' ','0',2,'1','TERMINAL_DATA_MANA_BTN_CLEAR') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('TERMINAL_TASK_MANA_BTN_ADD','TERMINAL_TASK_MANA','[按钮]添加任务','#',1,' ','0',2,'1','TERMINAL_TASK_MANA_BTN_ADD') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('TERMINAL_TASK_MANA_BTN_EDIT','TERMINAL_TASK_MANA','[按钮]编辑任务','#',2,' ','0',2,'1','TERMINAL_TASK_MANA_BTN_EDIT') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('TERMINAL_TASK_MANA_BTN_DEL','TERMINAL_TASK_MANA','[按钮]删除任务','#',3,' ','0',2,'1','TERMINAL_TASK_MANA_BTN_DEL') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('RULE_BUSI_MANA_BTN_ADD','RULE_BUSI_MANA','[按钮]添加','#',1,' ','0',2,'1','RULE_BUSI_MANA_BTN_ADD') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('RULE_BUSI_MANA_BTN_EDIT','RULE_BUSI_MANA','[按钮]编辑','#',2,' ','0',2,'1','RULE_BUSI_MANA_BTN_EDIT') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('RULE_BUSI_MANA_BTN_DEL','RULE_BUSI_MANA','[按钮]删除','#',3,' ','0',2,'1','RULE_BUSI_MANA_BTN_DEL') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('RULE_MA_MAIN_MANA_BTN_ADD','RULE_MA_MAIN_MANA','[按钮]添加','#',1,' ','0',2,'1','RULE_MA_MAIN_MANA_BTN_ADD') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('RULE_MA_MAIN_MANA_BTN_EDIT','RULE_MA_MAIN_MANA','[按钮]编辑','#',2,' ','0',2,'1','RULE_MA_MAIN_MANA_BTN_EDIT') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('RULE_MA_MAIN_MANA_BTN_DEL','RULE_MA_MAIN_MANA','[按钮]删除','#',3,' ','0',2,'1','RULE_MA_MAIN_MANA_BTN_DEL') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('RULE_MA_MAIN_MANA_BTN_MAP','RULE_MA_MAIN_MANA','[按钮]关联检验规则','#',4,' ','0',2,'1','RULE_MA_MAIN_MANA_BTN_MAP') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('RULE_MA_ASSIST_MANA_BTN_ADD','RULE_MA_ASSIST_MANA','[按钮]添加','#',1,' ','0',2,'1','RULE_MA_ASSIST_MANA_BTN_ADD') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('RULE_MA_ASSIST_MANA_BTN_EDIT','RULE_MA_ASSIST_MANA','[按钮]编辑','#',2,' ','0',2,'1','RULE_MA_ASSIST_MANA_BTN_EDIT') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('RULE_MA_ASSIST_MANA_BTN_DEL','RULE_MA_ASSIST_MANA','[按钮]删除','#',3,' ','0',2,'1','RULE_MA_ASSIST_MANA_BTN_DEL') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('RULE_MA_MAMAP_MANA_BTN_DEL','RULE_MA_MAMAP_MANA','[按钮]删除','#',3,' ','0',2,'1','RULE_MA_MAMAP_MANA_BTN_DEL') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('RULE_TEST_MANA_MANA_BTN_BIZ_ADD','RULE_TEST_MANA','[按钮]添加已有业务拨测','#',1,' ','0',2,'1','RULE_TEST_MANA_MANA_BTN_BIZ_ADD') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('RULE_TEST_MANA_MANA_BTN_NEW_ADD','RULE_TEST_MANA','[按钮]添加新业务拨测','#',2,' ','0',2,'1','RULE_TEST_MANA_MANA_BTN_NEW_ADD') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('RULE_TEST_MANA_BTN_EDIT','RULE_TEST_MANA','[按钮]编辑','#',3,' ','0',2,'1','RULE_TEST_MANA_BTN_EDIT') ; 
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('RULE_TEST_MANA_BTN_DEL','RULE_TEST_MANA','[按钮]删除','#',4,' ','0',2,'1','RULE_TEST_MANA_BTN_DEL') ; 


insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_0','BIG_USER_MANA_BTN_BLACK','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_1','BIG_BLACK_MANA_BTN_ADD','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_2','BIG_BLACK_MANA_BTN_EDIT','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_3','BIG_BLACK_MANA_BTN_DEL','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_4','BIG_FILTER_MANA_BTN_EDIT','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_5','SYSTEM_USER_MANA_BTN_ADD','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_6','SYSTEM_USER_MANA_BTN_EDIT','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_7','SYSTEM_USER_MANA_BTN_DEL','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_8','SYSTEM_USER_MANA_BTN_ROLE','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_9','SYSTEM_USER_MANA_BTN_UNMP','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_10','SYSTEM_ROLE_MANA_BTN_ADD','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_11','SYSTEM_ROLE_MANA_BTN_EDIT','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_12','SYSTEM_ROLE_MANA_BTN_DEL','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_13','SYSTEM_ROLE_MANA_BTN_ROLE','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_14','SYSTEM_MENU_MANA_BTN_ADD','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_15','SYSTEM_MENU_MANA_BTN_EDIT','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_16','SYSTEM_MENU_MANA_BTN_DEL','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_17','SYSTEM_LOG_MANA_BTN_DEL','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_18','CATCH_HISBASE_DATA_BTN_ADD','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_19','CATCH_HISBASE_DATA_BTN_EDIT','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_20','CATCH_HISBASE_DATA_BTN_PAUSE','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_21','CATCH_HISBASE_DATA_BTN_DEL','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_22','CATCH_CURRBASE_DATA_BTN_ADD','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_23','CATCH_CURRBASE_DATA_BTN_EDIT','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_24','CATCH_CURRBASE_DATA_BTN_PAUSE','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_25','CATCH_CURRBASE_DATA_BTN_DEL','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_26','CATCH_HISANALYSIS_DATA_BTN_ADD','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_27','CATCH_HISANALYSIS_DATA_BTN_EDIT','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_28','CATCH_HISANALYSIS_DATA_BTN_PAUSE','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_29','CATCH_HISANALYSIS_DATA_BTN_DEL','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_30','CATCH_IMSIS_DATA_BTN_ADD','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_31','CATCH_IMSIS_DATA_BTN_EDIT','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_32','CATCH_IMSIS_DATA_BTN_PAUSE','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_33','CATCH_IMSIS_DATA_BTN_DEL','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_34','TERMINAL_DATA_MANA_BTN_UPLOAD','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_35','TERMINAL_DATA_MANA_BTN_CLEAR','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_36','TERMINAL_TASK_MANA_BTN_ADD','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_37','TERMINAL_TASK_MANA_BTN_EDIT','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_38','TERMINAL_TASK_MANA_BTN_DEL','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_39','RULE_BUSI_MANA_BTN_ADD','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_40','RULE_BUSI_MANA_BTN_EDIT','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_41','RULE_BUSI_MANA_BTN_DEL','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_42','RULE_MA_MAIN_MANA_BTN_ADD','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_43','RULE_MA_MAIN_MANA_BTN_EDIT','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_44','RULE_MA_MAIN_MANA_BTN_DEL','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_45','RULE_MA_MAIN_MANA_BTN_MAP','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_46','RULE_MA_ASSIST_MANA_BTN_ADD','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_47','RULE_MA_ASSIST_MANA_BTN_EDIT','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_48','RULE_MA_ASSIST_MANA_BTN_DEL','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_49','RULE_MA_MAMAP_MANA_DEL','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_50','RULE_TEST_MANA_MANA_BTN_BIZ_ADD','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_51','RULE_TEST_MANA_MANA_BTN_NEW_ADD','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_52','RULE_TEST_MANA_BTN_EDIT','ROLEGROUP_4U00BQ7H');
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BASEROLEPERM_BTN_53','RULE_TEST_MANA_BTN_DEL','ROLEGROUP_4U00BQ7H');




--数据提取权限
insert into tbBasePermissions( id,vcParentId,vcMenuName,vcRedirectUrl,nmOrderNum,txtPermMemo,btDeleted,tiPermType,btShow,vcPermSymbol) values ('DATA_CATCH_USER_PERM','BUSINUSS_DATA_CATCH','[功能]数据提取任务权限','#',4,' ','0',9,'1','DATA_CATCH_USER_PERM') ; 
insert into tbBaseRolePermis(id,vcPermId,vcRoleId) values ('BUSI_1001','DATA_CATCH_USER_PERM','ROLEGROUP_4U00BQ7H');
